/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EnderecoController;
import Controller.UsuarioController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author luikt
 */
public class FrCadastrarUsuarioOuProfessor extends javax.swing.JFrame {

    UsuarioController usuarioController;
    EnderecoController enderecoController;

    /**
     * Creates new form FrMenuUsuario
     */
    public FrCadastrarUsuarioOuProfessor(UsuarioController usuarioController, EnderecoController enderecoController) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.usuarioController = usuarioController;
        this.enderecoController = enderecoController;
        buttonGroup.add(rbtNivel2Prof);
        buttonGroup.add(rbtNivel1Admin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paEndereco = new javax.swing.JPanel();
        jlbRua = new javax.swing.JLabel();
        jblNumero = new javax.swing.JLabel();
        jblComplemento = new javax.swing.JLabel();
        jblBairro = new javax.swing.JLabel();
        jblCidade = new javax.swing.JLabel();
        jblEstado = new javax.swing.JLabel();
        edtEstado = new javax.swing.JTextField();
        edtCidade = new javax.swing.JTextField();
        edtBairro = new javax.swing.JTextField();
        edtRua = new javax.swing.JTextField();
        edtNumero = new javax.swing.JTextField();
        edtComplemento = new javax.swing.JTextField();
        panDadosPessoais = new javax.swing.JPanel();
        jlbTelefone = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbCPF = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbSenha = new javax.swing.JLabel();
        edtCPF = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        edtDepartamento = new javax.swing.JTextField();
        jlbDepartamento1 = new javax.swing.JLabel();
        rbtNivel2Prof = new javax.swing.JRadioButton();
        rbtNivel1Admin = new javax.swing.JRadioButton();
        edtNome = new javax.swing.JTextField();
        edtSenha = new javax.swing.JTextField();
        jblTitulo = new javax.swing.JLabel();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbRua.setText("Rua");

        jblNumero.setText("Numero");

        jblComplemento.setText("Complemento");

        jblBairro.setText("Bairro");

        jblCidade.setText("Cidade");

        jblEstado.setText("Estado");

        edtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paEnderecoLayout = new javax.swing.GroupLayout(paEndereco);
        paEndereco.setLayout(paEnderecoLayout);
        paEnderecoLayout.setHorizontalGroup(
            paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblBairro)
                    .addComponent(jblEstado)
                    .addComponent(jblCidade)
                    .addComponent(jlbRua)
                    .addComponent(jblNumero)
                    .addComponent(jblComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addComponent(edtCidade)
                    .addComponent(edtBairro)
                    .addComponent(edtNumero)
                    .addComponent(edtComplemento)
                    .addComponent(edtRua))
                .addContainerGap())
        );
        paEnderecoLayout.setVerticalGroup(
            paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paEnderecoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblEstado)
                    .addComponent(edtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCidade)
                    .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblComplemento))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", paEndereco);

        jlbTelefone.setText("Telefone");

        jlbNome.setText("Nome");

        jlbCPF.setText("CPF");

        jlbEmail.setText("Email");

        jlbSenha.setText("Senha");

        edtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelefoneActionPerformed(evt);
            }
        });

        edtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDepartamentoActionPerformed(evt);
            }
        });

        jlbDepartamento1.setText("Departamento");

        rbtNivel2Prof.setText("Professor");
        rbtNivel2Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNivel2ProfActionPerformed(evt);
            }
        });

        rbtNivel1Admin.setText("Administrador");
        rbtNivel1Admin.setToolTipText("");
        rbtNivel1Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNivel1AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDadosPessoaisLayout = new javax.swing.GroupLayout(panDadosPessoais);
        panDadosPessoais.setLayout(panDadosPessoaisLayout);
        panDadosPessoaisLayout.setHorizontalGroup(
            panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDepartamento1)
                            .addComponent(jlbNome)
                            .addComponent(jlbCPF)
                            .addComponent(jlbEmail)
                            .addComponent(jlbSenha)
                            .addComponent(jlbTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(edtTelefone)
                            .addComponent(edtEmail)
                            .addComponent(edtCPF)
                            .addComponent(edtNome)
                            .addComponent(edtSenha)))
                    .addGroup(panDadosPessoaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbtNivel2Prof)
                        .addGap(18, 18, 18)
                        .addComponent(rbtNivel1Admin)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        panDadosPessoaisLayout.setVerticalGroup(
            panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDadosPessoaisLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCPF)
                    .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSenha)
                    .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTelefone)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDepartamento1)
                    .addComponent(edtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtNivel1Admin)
                    .addComponent(rbtNivel2Prof))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", panDadosPessoais);

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("Cadastro de Usuário");

        btnCadastrarUsuario.setText("Cadastrar");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelefoneActionPerformed

    private void edtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEstadoActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        getDadosForm();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    public void getDadosForm() {
        String nome = edtNome.getText();
        String cpf = edtCPF.getText();
        String email = edtEmail.getText();
        String senha = edtSenha.getText();
        String telefone = edtTelefone.getText();
        String departamento = edtDepartamento.getText();
        int nivelUsuario;
        if(rbtNivel1Admin.isSelected())
            nivelUsuario = 1;
        else
            nivelUsuario = 0;
        
            
        
        //endereco
        String estado = edtEstado.getText();
        String cidade = edtCidade.getText();
        String bairro = edtBairro.getText();
        String rua = edtRua.getText();
        String numero = edtNumero.getText();
        String complemento = edtComplemento.getText();

        //Dados do login do usuário
        if (email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!", "", 1);
        } else {
            //Passando todos os dados para o controlador
            enderecoController.adicionar(rua, numero, complemento, bairro, cidade, estado);
            usuarioController.adicionar(nome, cpf, email, senha, telefone, departamento, nivelUsuario);
            FrListarUsuarios x = new FrListarUsuarios();
            x.setVisible(true);
            this.dispose();
        }

    }

    public String validaCampos() {
        String nome = edtNome.getText();
        String cpf = edtCPF.getText();
        String email = edtEmail.getText();
        String senha = edtSenha.getText();
        String telefone = edtTelefone.getText();
        String departamento = edtDepartamento.getText();
        String estado = edtEstado.getText();
        String cidade = edtCidade.getText();
        String bairro = edtBairro.getText();
        String rua = edtRua.getText();
        String numero = edtNumero.getText();
        String complemento = edtComplemento.getText();

        String msgErro = "";
        if (nome.isEmpty()) {
            msgErro += "Nome não informado\n";
        }
        if (cpf.isEmpty()||cpf.equals("   .   .   -  ")) {
            msgErro += "CPF não informado\n";
        }
        if (email.isEmpty()) {
            msgErro += "Email não informado\n";
        }
        if (senha.isEmpty()) {
            msgErro += "Senha não informada\n";
        }
        if (telefone.isEmpty()) {
            msgErro += "Telefone não informado\n";
        }
        if (departamento.isEmpty()) {
            msgErro += "Departamento não informado\n";
        }
        if (!rbtNivel1Admin.isSelected() || !rbtNivel2Prof.isSelected()) {
            msgErro += "Escolha um nivel de acesso\n";
        }
        //EDERECO
        if (estado.isEmpty()) {
            msgErro += "Estado não informado\n";
        }
        if (cidade.isEmpty()) {
            msgErro += "Cidade não informado\n";
        }
        if (bairro.isEmpty()) {
            msgErro += "Bairro não informado\n";
        }
        if (rua.isEmpty()) {
            msgErro += "Rua não informada\n";
        }
        if (numero.isEmpty()) {
            msgErro += "Numero do Endereço não informado\n";
        }

        return msgErro;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrListarUsuarios x = new FrListarUsuarios();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDepartamentoActionPerformed

    private void rbtNivel2ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNivel2ProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNivel2ProfActionPerformed

    private void rbtNivel1AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNivel1AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNivel1AdminActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtComplemento;
    private javax.swing.JTextField edtDepartamento;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEstado;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JTextField edtRua;
    private javax.swing.JTextField edtSenha;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblBairro;
    private javax.swing.JLabel jblCidade;
    private javax.swing.JLabel jblComplemento;
    private javax.swing.JLabel jblEstado;
    private javax.swing.JLabel jblNumero;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel jlbCPF;
    private javax.swing.JLabel jlbDepartamento1;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbRua;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JPanel paEndereco;
    private javax.swing.JPanel panDadosPessoais;
    private javax.swing.JRadioButton rbtNivel1Admin;
    private javax.swing.JRadioButton rbtNivel2Prof;
    // End of variables declaration//GEN-END:variables
}
