/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author luikt
 */
public class FrEditarHorario extends javax.swing.JFrame {

    /**
     * Creates new form FrAdicionarHorario
     */
    public FrEditarHorario() {
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblTitulo = new javax.swing.JLabel();
        edtHoraInicial = new javax.swing.JTextField();
        edtHoraFinal = new javax.swing.JTextField();
        jlbHoraInicial = new javax.swing.JLabel();
        jlbHoraFinal = new javax.swing.JLabel();
        rbtSegunda = new javax.swing.JRadioButton();
        jlbDiasQueRepetem = new javax.swing.JLabel();
        rbtTerca = new javax.swing.JRadioButton();
        rbtQuinta = new javax.swing.JRadioButton();
        rbtSexta = new javax.swing.JRadioButton();
        rbtSabado = new javax.swing.JRadioButton();
        rbtQuarta = new javax.swing.JRadioButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("Editar Horário");

        jlbHoraInicial.setText("Hora Inicial");

        jlbHoraFinal.setText("Hora Final");

        rbtSegunda.setText("Segunda-Feira");
        rbtSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSegundaActionPerformed(evt);
            }
        });

        jlbDiasQueRepetem.setText("Selecione os Dias que Repetem ");

        rbtTerca.setText("Terça-Feira");
        rbtTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTercaActionPerformed(evt);
            }
        });

        rbtQuinta.setText("Quinta-Feira");
        rbtQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtQuintaActionPerformed(evt);
            }
        });

        rbtSexta.setText("Sexta-Feira");
        rbtSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSextaActionPerformed(evt);
            }
        });

        rbtSabado.setText("Sábado");
        rbtSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSabadoActionPerformed(evt);
            }
        });

        rbtQuarta.setText("Quarta-Feira");
        rbtQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtQuartaActionPerformed(evt);
            }
        });

        btnCadastrarUsuario.setText("Cadastrar");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDiasQueRepetem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtSegunda)
                                .addGap(18, 18, 18)
                                .addComponent(rbtTerca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtQuinta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbtSexta)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtSabado)
                            .addComponent(rbtQuarta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbHoraInicial)
                    .addComponent(jlbHoraFinal))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtHoraInicial)
                    .addComponent(edtHoraFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoraInicial)
                    .addComponent(edtHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jlbDiasQueRepetem)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtSegunda)
                    .addComponent(rbtQuarta)
                    .addComponent(rbtTerca))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtSexta)
                    .addComponent(rbtQuinta)
                    .addComponent(rbtSabado))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSegundaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSegundaActionPerformed

    private void rbtTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtTercaActionPerformed

    private void rbtQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtQuintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtQuintaActionPerformed

    private void rbtSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSextaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSextaActionPerformed

    private void rbtSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSabadoActionPerformed

    private void rbtQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtQuartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtQuartaActionPerformed

      public String validaCampos(){
        
       
        String horaFinal = edtHoraFinal.getText();
        String horaInicial = edtHoraInicial.getText();
        
        String msgErro = "";
        if(horaInicial.isEmpty())
            msgErro += "Favor Informar Hora Inicial\n";
        if(horaFinal.isEmpty())
            msgErro += "Favor Informar Hora Final\n";
        if(!rbtQuarta.isSelected() || !rbtQuinta.isSelected()|| !rbtSegunda.isSelected() || !rbtTerca.isSelected()|| !rbtSexta.isSelected())
            msgErro += "Selecione Pelo menos um dian";
        
        return msgErro;
    }
    
    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        String msgErro = this.validaCampos();
        JOptionPane.showMessageDialog(this, msgErro);

    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrEditarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrEditarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrEditarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrEditarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrEditarHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField edtHoraFinal;
    private javax.swing.JTextField edtHoraInicial;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel jlbDiasQueRepetem;
    private javax.swing.JLabel jlbHoraFinal;
    private javax.swing.JLabel jlbHoraInicial;
    private javax.swing.JRadioButton rbtQuarta;
    private javax.swing.JRadioButton rbtQuinta;
    private javax.swing.JRadioButton rbtSabado;
    private javax.swing.JRadioButton rbtSegunda;
    private javax.swing.JRadioButton rbtSexta;
    private javax.swing.JRadioButton rbtTerca;
    // End of variables declaration//GEN-END:variables
}
