/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Turma;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author luikt
 */
public class FrFichaTurma extends javax.swing.JFrame {

    /**
     * Creates new form JrFichaUsuario
     */
    public FrFichaTurma(Turma turma) {
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
       // setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        labPeriodo.setText(Integer.toString(turma.getPeriodoTurma()));
        labAnoSemestre.setText(turma.getAnoTurma() + "-" + turma.getSemestreTurma());
        labCurso.setText(turma.getCurso().getNome());
        labProfessor.setText(turma.getProfessor().getUsuario().getNome());
        labDisciplina.setText(turma.getDisciplina().getNomeDisciplina());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbCurso1 = new javax.swing.JLabel();
        jlbMatriz1 = new javax.swing.JLabel();
        labAnoSemestre = new javax.swing.JLabel();
        labCurso = new javax.swing.JLabel();
        labProfessor = new javax.swing.JLabel();
        jlbNome2 = new javax.swing.JLabel();
        labPeriodo = new javax.swing.JLabel();
        jlbMatriz2a = new javax.swing.JLabel();
        labDisciplina = new javax.swing.JLabel();
        jblTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jlbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbNome.setText("Ano");

        jlbCurso1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbCurso1.setText("Curso");

        jlbMatriz1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbMatriz1.setText("Professor");

        labAnoSemestre.setText("2019.1");

        labCurso.setText("Ciência da COmputação");

        labProfessor.setText("PPC[2124]");

        jlbNome2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbNome2.setText("Periodo");

        labPeriodo.setText("6º");

        jlbMatriz2a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbMatriz2a.setText("Disciplina");

        labDisciplina.setText("dasdasda");

        javax.swing.GroupLayout panUsuarioLayout = new javax.swing.GroupLayout(panUsuario);
        panUsuario.setLayout(panUsuarioLayout);
        panUsuarioLayout.setHorizontalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2))
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCurso1)
                            .addComponent(jlbMatriz1)
                            .addComponent(jlbNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labCurso)
                                .addComponent(labPeriodo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labAnoSemestre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(labProfessor)))
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbNome2))
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbMatriz2a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labDisciplina)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panUsuarioLayout.setVerticalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome2)
                    .addComponent(labPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNome)
                            .addComponent(labAnoSemestre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbCurso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbMatriz1))
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addComponent(labCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labProfessor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMatriz2a)
                    .addComponent(labDisciplina))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jblTitulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo1.setText("Ficha da Turma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jblTitulo1;
    private javax.swing.JLabel jlbCurso1;
    private javax.swing.JLabel jlbMatriz1;
    private javax.swing.JLabel jlbMatriz2a;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbNome2;
    private javax.swing.JLabel labAnoSemestre;
    private javax.swing.JLabel labCurso;
    private javax.swing.JLabel labDisciplina;
    private javax.swing.JLabel labPeriodo;
    private javax.swing.JLabel labProfessor;
    private javax.swing.JPanel panUsuario;
    // End of variables declaration//GEN-END:variables
}
