/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author luikt
 */
public class FrInicioAdm extends javax.swing.JFrame {

    /**
     * Creates new form FrIniciarAdm
     */
    public FrInicioAdm() {
        super("OnTime");
        //TELA CHEIA 
        this.setExtendedState(MAXIMIZED_BOTH);  
        initComponents();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        //teste de integracao 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitulo = new javax.swing.JLabel();
        panUsuario = new javax.swing.JPanel();
        jlbIcon = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbCPF = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbTelefone = new javax.swing.JLabel();
        jlbDepartamento = new javax.swing.JLabel();
        jlbEndereco = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labDepartamento = new javax.swing.JLabel();
        labEmail = new javax.swing.JLabel();
        labCPF = new javax.swing.JLabel();
        labTelefone = new javax.swing.JLabel();
        labPEC = new javax.swing.JLabel();
        labBRN = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnAdministrador = new javax.swing.JMenu();
        mniEditarMEusDados = new javax.swing.JMenuItem();
        mniExcluirConta = new javax.swing.JMenuItem();
        mniTrocarSenha = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();
        jmnUsuario = new javax.swing.JMenu();
        mniNovoUsuaio = new javax.swing.JMenuItem();
        mniListarUsuarios = new javax.swing.JMenuItem();
        mnuHorario = new javax.swing.JMenu();
        mniNovoHorario = new javax.swing.JMenuItem();
        mniListarHorarios = new javax.swing.JMenuItem();
        mnuProfessor = new javax.swing.JMenu();
        mniNovoProfessor = new javax.swing.JMenuItem();
        mniListarProfessores = new javax.swing.JMenuItem();
        mnuTurma = new javax.swing.JMenu();
        mniNovaTurma = new javax.swing.JMenuItem();
        mniListarTurmas = new javax.swing.JMenuItem();
        mnu = new javax.swing.JMenu();
        mniNovaDisciplina = new javax.swing.JMenuItem();
        mniListarDisciplinas = new javax.swing.JMenuItem();
        mnuCurso = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitulo.setText(" OnTime");

        panUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jlbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbNome.setText("Nome");

        jlbCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbCPF.setText("CPF");

        jlbEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbEmail.setText("Email");

        jlbTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbTelefone.setText("Telefone");

        jlbDepartamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbDepartamento.setText("Departamento");

        jlbEndereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbEndereco.setText("Endereço");

        labNome.setText("Luiza");

        labDepartamento.setText("DACC");

        labEmail.setText("luikta@gmail.com");

        labCPF.setText("099,555,666-25");

        labTelefone.setText("(32) 98480-5202");

        labPEC.setText("Brasil, MG, Rio Pomba");

        labBRN.setText("Centro, Rua Doutor Queiroz, 193");

        javax.swing.GroupLayout panUsuarioLayout = new javax.swing.GroupLayout(panUsuario);
        panUsuario.setLayout(panUsuarioLayout);
        panUsuarioLayout.setHorizontalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTelefone)
                    .addComponent(jlbCPF)
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addComponent(jlbEndereco)
                        .addGap(10, 10, 10)
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlbIcon)
                                .addComponent(labCPF)
                                .addComponent(labTelefone))
                            .addGroup(panUsuarioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labBRN)
                                    .addComponent(labPEC)))))
                    .addGroup(panUsuarioLayout.createSequentialGroup()
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDepartamento)
                            .addComponent(jlbNome)
                            .addComponent(jlbEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEmail)
                            .addComponent(labNome)
                            .addComponent(labDepartamento))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panUsuarioLayout.setVerticalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbIcon)
                .addGap(25, 25, 25)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(labNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDepartamento)
                    .addComponent(labDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(labEmail))
                .addGap(3, 3, 3)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCPF)
                    .addComponent(labCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTelefone)
                    .addComponent(labTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEndereco)
                    .addComponent(labPEC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labBRN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jmnAdministrador.setText("Administrador");

        mniEditarMEusDados.setText("Editar Meus Dados");
        mniEditarMEusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditarMEusDadosActionPerformed(evt);
            }
        });
        jmnAdministrador.add(mniEditarMEusDados);

        mniExcluirConta.setText("Excluir conta");
        mniExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExcluirContaActionPerformed(evt);
            }
        });
        jmnAdministrador.add(mniExcluirConta);

        mniTrocarSenha.setText("Trocar Senha");
        mniTrocarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTrocarSenhaActionPerformed(evt);
            }
        });
        jmnAdministrador.add(mniTrocarSenha);

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        jmnAdministrador.add(mniSair);

        jMenuBar1.add(jmnAdministrador);

        jmnUsuario.setText("Usuario");

        mniNovoUsuaio.setText("Novo Usuario");
        mniNovoUsuaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoUsuaioActionPerformed(evt);
            }
        });
        jmnUsuario.add(mniNovoUsuaio);

        mniListarUsuarios.setText("Usuários");
        mniListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarUsuariosActionPerformed(evt);
            }
        });
        jmnUsuario.add(mniListarUsuarios);

        jMenuBar1.add(jmnUsuario);

        mnuHorario.setText("Horario");

        mniNovoHorario.setText("Novo Horario");
        mniNovoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoHorarioActionPerformed(evt);
            }
        });
        mnuHorario.add(mniNovoHorario);

        mniListarHorarios.setText("Horarios");
        mniListarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarHorariosActionPerformed(evt);
            }
        });
        mnuHorario.add(mniListarHorarios);

        jMenuBar1.add(mnuHorario);

        mnuProfessor.setText("Professor");
        mnuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfessorActionPerformed(evt);
            }
        });

        mniNovoProfessor.setText("Novo Professor");
        mniNovoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovoProfessorActionPerformed(evt);
            }
        });
        mnuProfessor.add(mniNovoProfessor);

        mniListarProfessores.setText("Professores");
        mniListarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarProfessoresActionPerformed(evt);
            }
        });
        mnuProfessor.add(mniListarProfessores);

        jMenuBar1.add(mnuProfessor);

        mnuTurma.setText("Turma");

        mniNovaTurma.setText("Nova Turma");
        mniNovaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovaTurmaActionPerformed(evt);
            }
        });
        mnuTurma.add(mniNovaTurma);

        mniListarTurmas.setText("Turmas");
        mniListarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarTurmasActionPerformed(evt);
            }
        });
        mnuTurma.add(mniListarTurmas);

        jMenuBar1.add(mnuTurma);

        mnu.setText("Disciplina");

        mniNovaDisciplina.setText("Nova Disciplina");
        mniNovaDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovaDisciplinaActionPerformed(evt);
            }
        });
        mnu.add(mniNovaDisciplina);

        mniListarDisciplinas.setText("Disciplinas");
        mniListarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarDisciplinasActionPerformed(evt);
            }
        });
        mnu.add(mniListarDisciplinas);

        jMenuBar1.add(mnu);

        mnuCurso.setText("Curso");
        mnuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCursoActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuCurso);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
            .addComponent(panUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniNovaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovaDisciplinaActionPerformed
        FrAdicionarDisciplina adicionarDisciplina = new FrAdicionarDisciplina();
        adicionarDisciplina.setVisible(true);
        
    }//GEN-LAST:event_mniNovaDisciplinaActionPerformed

    private void mniNovoUsuaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoUsuaioActionPerformed
        // TODO add your handling code here:
//        FrCadastrarUsuarioOuProfessor telaCadastro = new FrCadastrarUsuarioOuProfessor();
        //telaCadastro.setVisible(true);
                
    }//GEN-LAST:event_mniNovoUsuaioActionPerformed

    private void mnuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProfessorActionPerformed

    private void mniEditarMEusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditarMEusDadosActionPerformed
        FrProfessorEditarDados telaEditarDados = new FrProfessorEditarDados();
        telaEditarDados.setVisible(true);
    }//GEN-LAST:event_mniEditarMEusDadosActionPerformed

    private void mniExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExcluirContaActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir a conta?");
        // 0=yes, 1=no, 2=cancel
        System.out.println(opcao);
    }//GEN-LAST:event_mniExcluirContaActionPerformed

    private void mniTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTrocarSenhaActionPerformed
        FrMudarSenhaLogado telaMudarSenhaLogado = new FrMudarSenhaLogado();
        telaMudarSenhaLogado.setVisible(true);
    }//GEN-LAST:event_mniTrocarSenhaActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
       int opcao = JOptionPane.showConfirmDialog(null, 
                "Deseja sair?", "Sair", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        // 0=ok, 2=cancel
        System.out.println(opcao);
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarUsuariosActionPerformed
        FrListarUsuarios listarUsuarios = new FrListarUsuarios();
        listarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_mniListarUsuariosActionPerformed

    private void mniNovoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoHorarioActionPerformed
       FrAdicionarHorario adicionarHorario = new FrAdicionarHorario();
       adicionarHorario.setVisible(true);
        
    }//GEN-LAST:event_mniNovoHorarioActionPerformed

    private void mniListarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarHorariosActionPerformed
        FrListarHorario listarHorario = new FrListarHorario();
        listarHorario.setVisible(true);
        
    }//GEN-LAST:event_mniListarHorariosActionPerformed

    private void mniNovoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovoProfessorActionPerformed
       
        FrAdicionarProfessor cadastrarProfessor = new FrAdicionarProfessor();
        cadastrarProfessor.setVisible(true);
    }//GEN-LAST:event_mniNovoProfessorActionPerformed

    private void mniNovaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovaTurmaActionPerformed
        FrAdicionarTurma telaNovaTurma = new FrAdicionarTurma();
        telaNovaTurma.setVisible(true);

    }//GEN-LAST:event_mniNovaTurmaActionPerformed

    private void mniListarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarTurmasActionPerformed
        FrListarTurma telaListarTurmas = new FrListarTurma();
        telaListarTurmas.setVisible(true);
        
    }//GEN-LAST:event_mniListarTurmasActionPerformed

    private void mniListarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarDisciplinasActionPerformed
       FrListarDisciplinas telaDisciplinas = new FrListarDisciplinas();
       telaDisciplinas.setVisible(true);
        
    }//GEN-LAST:event_mniListarDisciplinasActionPerformed

    private void mniListarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarProfessoresActionPerformed
        FrListarProfessor listarProfessor = new FrListarProfessor();
        listarProfessor.setVisible(true);
    }//GEN-LAST:event_mniListarProfessoresActionPerformed

    private void mnuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCursoActionPerformed
       FrAdicionarCurso adicionarCurso = new FrAdicionarCurso();
        adicionarCurso.setVisible(true);
    }//GEN-LAST:event_mnuCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInicioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInicioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInicioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInicioAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrInicioAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlbCPF;
    private javax.swing.JLabel jlbDepartamento;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbEndereco;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbTelefone;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JMenu jmnAdministrador;
    private javax.swing.JMenu jmnUsuario;
    private javax.swing.JLabel labBRN;
    private javax.swing.JLabel labCPF;
    private javax.swing.JLabel labDepartamento;
    private javax.swing.JLabel labEmail;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labPEC;
    private javax.swing.JLabel labTelefone;
    private javax.swing.JMenuItem mniEditarMEusDados;
    private javax.swing.JMenuItem mniExcluirConta;
    private javax.swing.JMenuItem mniListarDisciplinas;
    private javax.swing.JMenuItem mniListarHorarios;
    private javax.swing.JMenuItem mniListarProfessores;
    private javax.swing.JMenuItem mniListarTurmas;
    private javax.swing.JMenuItem mniListarUsuarios;
    private javax.swing.JMenuItem mniNovaDisciplina;
    private javax.swing.JMenuItem mniNovaTurma;
    private javax.swing.JMenuItem mniNovoHorario;
    private javax.swing.JMenuItem mniNovoProfessor;
    private javax.swing.JMenuItem mniNovoUsuaio;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniTrocarSenha;
    private javax.swing.JMenu mnu;
    private javax.swing.JMenu mnuCurso;
    private javax.swing.JMenu mnuHorario;
    private javax.swing.JMenu mnuProfessor;
    private javax.swing.JMenu mnuTurma;
    private javax.swing.JPanel panUsuario;
    // End of variables declaration//GEN-END:variables
}
