/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EnderecoController;
import Controller.UsuarioController;
import Model.Endereco;
import Model.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import relatorio.Relatorio;

/**
 *
 * @author luikt
 */
public final class FrListarUsuarios extends javax.swing.JFrame {

    EnderecoController enderecoController = new EnderecoController();
    UsuarioController usuarioController = new UsuarioController(4, enderecoController);
    ArrayList<Usuario> pdf = new ArrayList<>();
    DefaultTableModel tableModel;

    /**
     * Creates new form FrListarUsuarios
     */
    public FrListarUsuarios() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);

        carregarListaUsuarios();
    }

    public void carregarListaUsuarios() {
        ArrayList<Usuario> lista = usuarioController.getLista();
        String[] columnNames = {"idUsuario", "nomeUsuario", "cpfUsuario", "emailUsuario", "senhaUsuario", "telefoneUsuario", "departamentoUsuario", "nivelUsuario", "idEndereco", "ruaEndereco", "numeroEndereco", "complementoEndereco", "bairroEndereco", "cidadeEndereco", "estadoEndereco"};
        tableModel = new DefaultTableModel(columnNames, 0);
        //idu, nome, cpf, email, senha, telefone, departamento, nivel
        //ide, rua, numero, complemento, bairro, cidade, estado
        for (int i = 0; i < lista.size(); i++) {
            int id = lista.get(i).getIdUsuario();
            String nome = lista.get(i).getNome();
            String cpf = lista.get(i).getCpf();
            String email = lista.get(i).getEmail();
            String senha = lista.get(i).getSenha();
            String telefone = lista.get(i).getTelefone();
            String departamento = lista.get(i).getDepartamento();
            int nivel = lista.get(i).getNivelDeAcesso();

            int idE = lista.get(i).getEndereco().getIdEndereco();
            String rua = lista.get(i).getEndereco().getRuaEndereco();
            String numero = lista.get(i).getEndereco().getNumeroEndereco();
            String complemento = lista.get(i).getEndereco().getComplementoEndereco();
            String bairro = lista.get(i).getEndereco().getBairroEndereco();
            String cidade = lista.get(i).getEndereco().getCidadeEndereco();
            String estado = lista.get(i).getEndereco().getEstadoEndereco();

            //System.out.println(tipo + nome + departamento);
            String[] data = {Integer.toString(id), nome, cpf, email, senha, telefone, departamento, Integer.toString(nivel), Integer.toString(idE), rua, numero, complemento, bairro, cidade, estado};

            tableModel.addRow(data);
        }
        tblUsuarios.setModel(tableModel);
        spnListarusuario.setViewportView(tblUsuarios);
        //deixando na tabela e removendo da visualização

//
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(0));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(2 - 1));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(3 - 2));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(4 - 3));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(5 - 4));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(8 - 5));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(9 - 6));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(10 - 7));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(11 - 8));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(12 - 9));
        tblUsuarios.removeColumn(tblUsuarios.getColumnModel().getColumn(14 - 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnListarusuario = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnSaibaMais = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        btnAdicionar = new javax.swing.JToggleButton();
        jblTitulo = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnListarusuario.setViewportView(tblUsuarios);

        btnSaibaMais.setText("Saiba Mais");
        btnSaibaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaibaMaisActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("Usuários");

        btnCancelar2.setText("Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setText("Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnListarusuario)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSaibaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGerarRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnListarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaibaMais)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAdicionar)
                    .addComponent(btnCancelar2)
                    .addComponent(btnGerarRelatorio))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
//        FrCadastrarUsuarioOuProfessor telaEditarUsuario = new FrCadastrarUsuarioOuProfessor();
//        telaEditarUsuario.setVisible(true);
        EnderecoController enderecoController = new EnderecoController();
        UsuarioController usuarioController = new UsuarioController(1, enderecoController);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //carrego dados nos campos
        //idu, ide, nome, cpf, email, senha, telefone, dept, nivel

        Usuario user = new Usuario();
        int row = tblUsuarios.getSelectedRow();
        //seta os dados do usuario
        //idu, nome, cpf, email, senha, telefone, departamento, nivel
        //ide, rua, numero, complemento, bairro, cidade, estado

        String idUsuario = tblUsuarios.getModel().getValueAt(row, 0).toString();
        user.setIdUsuario(Integer.parseInt(idUsuario));

        String nome = tblUsuarios.getModel().getValueAt(row, 1).toString();
        user.setNome(nome);

        String cpf = tblUsuarios.getModel().getValueAt(row, 2).toString();
        user.setCpf(cpf);

        String email = tblUsuarios.getModel().getValueAt(row, 3).toString();
        user.setEmail(email);

        String senha = tblUsuarios.getModel().getValueAt(row, 4).toString();
        user.setSenha(senha);

        String telefone = tblUsuarios.getModel().getValueAt(row, 5).toString();
        user.setTelefone(telefone);

        String departamento = tblUsuarios.getModel().getValueAt(row, 6).toString();
        user.setDepartamento(departamento);

        String nivel = tblUsuarios.getModel().getValueAt(row, 7).toString();
        user.setNivelDeAcesso(Integer.parseInt(nivel));

        //seta os dados do endereco
        Endereco address = new Endereco();

        String idEndereco = tblUsuarios.getModel().getValueAt(row, 8).toString();
        address.setIdEndereco(Integer.parseInt(idEndereco));

        String rua = tblUsuarios.getModel().getValueAt(row, 9).toString();
        address.setRuaEndereco(rua);

        String numero = tblUsuarios.getModel().getValueAt(row, 10).toString();
        address.setNumeroEndereco(numero);

        String complemento = tblUsuarios.getModel().getValueAt(row, 11).toString();
        address.setComplementoEndereco(complemento);

        String bairro = tblUsuarios.getModel().getValueAt(row, 12).toString();
        address.setBairroEndereco(bairro);

        String cidade = tblUsuarios.getModel().getValueAt(row, 13).toString();
        address.setCidadeEndereco(cidade);

        String estado = tblUsuarios.getModel().getValueAt(row, 14).toString();
        address.setEstadoEndereco(estado);

        user.setEndereco(address);

        System.out.println("id clicado eh " + idUsuario);
        usuarioController = new UsuarioController(2, user);

        this.dispose();


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSaibaMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaibaMaisActionPerformed
        //consultar e o id do campo q clicou
        String value = tblUsuarios.getModel().getValueAt(0, 0).toString();
        UsuarioController usuarioController = new UsuarioController(4,value);
        FrFichaUsuario telaFichaUsuario = new FrFichaUsuario();
        telaFichaUsuario.setVisible(true);
    }//GEN-LAST:event_btnSaibaMaisActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir a conta?");
        // 0=yes, 1=no, 2=cancel    
        System.out.println(opcao);
        if (opcao == 0) {
            int row = tblUsuarios.getSelectedRow();
            String value = tblUsuarios.getModel().getValueAt(row, 0).toString();
            System.out.println("id clicado eh " + value);
            UsuarioController usuarioController = new UsuarioController();
            usuarioController.excluir(Integer.parseInt(value));
            this.dispose();
            FrListarUsuarios frlist = new FrListarUsuarios();
            frlist.setVisible(true);

        }


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        //idu, nome, cpf, email, senha, telefone, departamento, nivel
        //ide, rua, numero, complemento, bairro, cidade, estado
        for (int count = 0; count < tableModel.getRowCount(); count++) {
            Usuario user = new Usuario();
            user.setNome(tableModel.getValueAt(count, 1).toString());
            user.setCpf(tableModel.getValueAt(count, 2).toString());
            user.setEmail(tableModel.getValueAt(count, 3).toString());
            user.setSenha(tableModel.getValueAt(count, 4).toString());
            user.setTelefone(tableModel.getValueAt(count, 5).toString());
            user.setDepartamento(tableModel.getValueAt(count, 6).toString());
            pdf.add(user);
        }
        //setar os atributos bla bla

        Relatorio relatorio = new Relatorio();
        try {
            relatorio.gerarRelatorio(pdf);
        } catch (JRException ex) {
            Logger.getLogger(FrListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrListarUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrListarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JToggleButton btnSaibaMais;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JScrollPane spnListarusuario;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
