/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TurmaController;
import Controller.UsuarioController;
import Model.Curso;
import Model.Disciplina;
import Model.Endereco;
import Model.Professor;
import Model.Turma;
import Model.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luikt
 */
public class FrListarTurma extends javax.swing.JFrame {

    TurmaController turmaController = new TurmaController(4);
    DefaultTableModel tableModel;

    /**
     * Creates new form FrListarUsuarios
     */
    public FrListarTurma() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);

        carregarListaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();
        btnAdicionar = new javax.swing.JToggleButton();
        jblTitulo = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        btnSaibaMais = new javax.swing.JToggleButton();
        spnListarTurmas = new javax.swing.JScrollPane();
        tblTurmas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTitulo.setText("Turmas");

        btnCancelar2.setText("Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        btnSaibaMais.setText("Ver mais");
        btnSaibaMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaibaMaisActionPerformed(evt);
            }
        });

        spnListarTurmas.setViewportView(tblTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSaibaMais, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnListarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spnListarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAdicionar)
                    .addComponent(btnCancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaibaMais))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarListaUsuarios() {
        ArrayList<Turma> lista = turmaController.getLista();
        String[] columnNames = {"idTurma", "idCurso", "idDisciplina", "idProfessor",
            "nomeDisciplina", "nomeCurso", "nomeProfessor",
            "anoTurma", "salaTurma", "semestreTurma", "periodoTurma",};
        tableModel = new DefaultTableModel(columnNames, 0);
        System.out.println("lista size = " + lista.size());
        for (int i = 0; i < lista.size(); i++) {
            //professor
            int idP = lista.get(i).getProfessor().getId();
            String nomeP = lista.get(i).getProfessor().getUsuario().getNome();
            System.out.println("o id ehhhhhh" + idP);
            //disciplina
            int idD = lista.get(i).getDisciplina().getIdDisciplina();
            String nomeD = lista.get(i).getDisciplina().getNomeDisciplina();

            //curso
            int idC = lista.get(i).getIdCurso();
            String nomeC = lista.get(i).getCurso().getNome();

            //turma
            int idT = lista.get(i).getIdTurma();
            int anoT = lista.get(i).getAnoTurma();
            String salaT = lista.get(i).getSalaTurma();
            int semestreT = lista.get(i).getSemestreTurma();
            int periodoT = lista.get(i).getPeriodoTurma();
            //idt, idp, idd, idc, nomed, nomec, nomep, anot, salat, semestret, periodot
            String[] data = {Integer.toString(idT), Integer.toString(idC), Integer.toString(idD), Integer.toString(idP),
                nomeD, nomeC, nomeP, Integer.toString(anoT), salaT, Integer.toString(semestreT), Integer.toString(periodoT),};

            tableModel.addRow(data);
        }
        tblTurmas.setModel(tableModel);
        spnListarTurmas.setViewportView(tblTurmas);
        //deixando na tabela e removendo da visualização

//
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(0));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(0));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(0));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(0));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(6));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(5));
        tblTurmas.removeColumn(tblTurmas.getColumnModel().getColumn(4));

    }


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        this.dispose();
        TurmaController turmaController = new TurmaController(1);
        
      
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        FrEditarTurma telaEditarTurma = new FrEditarTurma();
        telaEditarTurma.setVisible(true);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir o horário?");
        // 0=yes, 1=no, 2=cancel
        
        System.out.println(opcao);

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnSaibaMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaibaMaisActionPerformed
        Turma turma = new Turma();
        int row = tblTurmas.getSelectedRow();
        //idt, idp, idd, idc, nomed, nomec, nomep, anot, salat, semestret, periodot
        //idt, idc, idd, idp

        Disciplina d = new Disciplina();
        String nomeD = tblTurmas.getModel().getValueAt(row, 4).toString();
        d.setNomeDisciplina(nomeD);
        turma.setDisciplina(d);

        String nomeC = tblTurmas.getModel().getValueAt(row, 5).toString();
        Curso c = new Curso();
        c.setNome(nomeC);
        turma.setCurso(c);

        String nomeP = tblTurmas.getModel().getValueAt(row, 6).toString();
        Professor p = new Professor();
        
        Usuario u = new Usuario();
        u.setNome(nomeP);
        p.setUsuario(u);
        turma.setProfessor(p);

        String anoT = tblTurmas.getModel().getValueAt(row, 7).toString();
        turma.setAnoTurma(Integer.parseInt(anoT));

        String salaT = tblTurmas.getModel().getValueAt(row, 8).toString();
        turma.setSalaTurma(salaT);

        String semestreT = tblTurmas.getModel().getValueAt(row, 9).toString();
        turma.setSemestreTurma(Integer.parseInt(semestreT));

        String periodoT = tblTurmas.getModel().getValueAt(row, 10).toString();
        turma.setPeriodoTurma(Integer.parseInt(periodoT));

        TurmaController turmaController = new TurmaController(turma);

    }//GEN-LAST:event_btnSaibaMaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrListarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrListarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrListarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrListarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrListarTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnSaibaMais;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JScrollPane spnListarTurmas;
    private javax.swing.JTable tblTurmas;
    // End of variables declaration//GEN-END:variables
}
